steps:
  # 1. Build the Docker image using Cloud Build Substitution Variables
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg", "NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL"
      - "--build-arg", "NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY"
      - "--build-arg", "NEXT_PUBLIC_CLOUDFRONT_PATH=$_NEXT_PUBLIC_CLOUDFRONT_PATH"
      - "--build-arg", "NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN=$_NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN"
      - "--build-arg", "NEXT_PUBLIC_POSTHOG_HOST=$_NEXT_PUBLIC_POSTHOG_HOST"
      - "-t", "gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA",
      - "."

  # 2. Push the built image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/://google.com"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "nextjs-app"
      - "--image=gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
